export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const FILTER_BY_REGION = 'FILTER_BY_REGION'
export const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY'
export const ORDER_BY = 'ORDER_BY'
export const GET_QUERY_COUNTRY = 'GET_QUERY_COUNTRY'
export const POST_ACTIVITY = 'POST_ACTIVITY'
export const GET_DETAIL= 'GET_DETAIL'

